export const bestOfferCity = [
  {
    image: "https://i.postimg.cc/XYZG0F8b/darak.jpg",
    country: "iran",
    location: "darak",
    city: "sistanAndBaluchestan",
    price: "400",
  },
  {
    image: "https://i.postimg.cc/3wxKTH7D/shahzade-mahan-garden.jpg",
    country: "iran",
    location: "mahan-garden",
    city: "kerman",
    price: "250",
  },
  {
    image: "https://i.postimg.cc/WpXwNGMF/ghajar-musuem.jpg",
    country: "iran",
    location: "ghajar-musuem",
    city: "tabriz",
    price: "250",
  },
  {
    image: "https://i.postimg.cc/76vwTJ0S/shahgoli.jpg",
    country: "iran",
    location: "shahgoli",
    city: "tabriz",
    price: "350",
  },
  {
    image: "https://i.postimg.cc/nzVT204x/pisa-tower.jpg",
    country: "italy",
    location: "pisa-tower",
    city: "pisa",
    price: "450",
  },
  {
    image: "https://i.postimg.cc/d1XdCBn4/pompeii.jpg",
    country: "italy",
    location: "pompeii",
    city: "pompeii",
    price: "500",
  },
  {
    image: "https://i.postimg.cc/hjJ7CztC/torino-palace.jpg",
    country: "italy",
    location: "torino-palace",
    city: "torino",
    price: "350",
  },
  {
    image:
      "https://i.postimg.cc/CKR1Yyp5/21-1-rome-italy-Baths-of-Caracalla.jpg",
    country: "italy",
    location: "rome",
    city: "Baths-of-Caracalla",
    price: "250",
  },
  {
    image: "https://i.postimg.cc/vBLdwXTD/alhambra.jpg",
    country: "spain",
    location: "granada",
    city: "alhambra",
    price: "300",
  },
  {
    image: "https://i.postimg.cc/br70000H/giralda-town.jpg",
    country: "spain",
    location: "giralda-town",
    city: "seville",
    price: "300",
  },
  {
    image: "https://i.postimg.cc/j2bPLqRZ/sanisidro-church.jpg",
    country: "spain",
    location: "sanisidro-church",
    city: "seville",
    price: "200",
  },
  {
    image: "https://i.postimg.cc/Kjx3m95W/7-debod.jpg",
    country: "spain",
    location: "debod",
    city: "madrid",
    price: "400",
  },
  {
    image: "https://i.postimg.cc/VNg37vVb/galata-tower.jpg",
    country: "turkey",
    location: "galata-tower",
    city: "istanbul",
    price: "350",
  },
  {
    image: "https://i.postimg.cc/PJs9JDL9/topkapi-palace.jpg",
    country: "turkey",
    location: "topkapi-palace",
    city: "istanbul",
    price: "250",
  },
  {
    image: "https://i.postimg.cc/5Ntqv0wR/hamamono-ankara.jpg",
    country: "turkey",
    location: "hamamono-ankara",
    city: "ankara",
    price: "450",
  },
  {
    image: "https://i.postimg.cc/C5R5hWqm/ayasufiye-mosque.jpg",
    country: "turkey",
    location: "ayasufiye-mosque",
    city: "istanbul",
    price: "200",
  },
];
