export const citiesOfIranData = [
  {id:1,
    image: "https://i.postimg.cc/zvk8H7hW/badab-suret-sari.jpg",
    townName: "Mazandaran",
  },
  {id:2,
    image: "https://i.postimg.cc/QxkJVTy3/perspolis-shiraz.jpg",
    townName: "Shiraz",
  },
  {id:3,
    image: "https://i.postimg.cc/Mp2gJVjJ/tabatabaii-House-isfahan.jpg",
    townName: "Isfahan",
  },
  {id:4,
    image: "https://i.postimg.cc/FzhgxFYq/lavan-island.jpg",
    townName: "Hormozgan",
  },
  {id:5,
    image: "https://i.postimg.cc/R0R0HMzq/dowlat-Abad-Garden-yazd.jpg",
    townName: "Yazd",
  },
  {id:6,
    image: "https://i.postimg.cc/zvk8H7hW/badab-suret-sari.jpg",
    townName: "Mazandaran",
  },
  {id:7,
    image: "https://i.postimg.cc/QxkJVTy3/perspolis-shiraz.jpg",
    townName: "Shiraz",
  },
  {id:8,
    image: "https://i.postimg.cc/Mp2gJVjJ/tabatabaii-House-isfahan.jpg",
    townName: "Isfahan",
  },
 
];

export const citiesOfItalyData = [
  {id:1,
    image: "https://i.postimg.cc/4NGzgVzJ/8-4.jpg",
    townName: "Florence",
  },
  {id:2,
    image: "https://i.postimg.cc/3NGNRCxs/Piazza-San-Marco.jpg",
    townName: "Venice",
  },
  {id:3,
    image:
      "https://i.postimg.cc/L4kMHb9H/21-1-rome-italy-Baths-of-Caracalla.jpg",
    townName: "Rome",
  },
  {id:4,
    image: "https://i.postimg.cc/Kc6TmM1N/uffizy-gallery.jpg",
    townName: "Florence",
  },
  {id:5,
    image:
      "https://i.postimg.cc/5y824pyW/18-1-rome-italy-Museo-Casina-delle-Civette.jpg",
    townName: "Rome",
  },
  {id:6,
    image: "https://i.postimg.cc/4NGzgVzJ/8-4.jpg",
    townName: "Florence",
  },
  {id:7,
    image: "https://i.postimg.cc/3NGNRCxs/Piazza-San-Marco.jpg",
    townName: "Venice",
  },
  {id:8,
    image:
      "https://i.postimg.cc/L4kMHb9H/21-1-rome-italy-Baths-of-Caracalla.jpg",
    townName: "Rome",
  },
 
];

export const citiesOfSpainData = [
  {id:1,
    image: "https://i.postimg.cc/qqrcpRkx/sagrada-Familia-Church.jpg",
    townName: "Barselona",
  },
  {id:2,
    image: "https://i.postimg.cc/brFv3CFS/7-debod.jpg",
    townName: "Madrid",
  },
  {id:3,
    image: "https://i.postimg.cc/MTQ9GjS8/4-Royal-Palace-1.jpg",
    townName: "Madrid",
  },
  {id:4,
    image: "https://i.postimg.cc/mr2xhjXW/pedralbes-Monestir.jpg",
    townName: "Barselona",
  },
  {id:5,
    image: "https://i.postimg.cc/8P6G2z70/5-La-Lonja.jpg",
    townName: "Valencia",
  },
  {id:6,
    image: "https://i.postimg.cc/qqrcpRkx/sagrada-Familia-Church.jpg",
    townName: "Barselona",
  },
  {id:7,
    image: "https://i.postimg.cc/brFv3CFS/7-debod.jpg",
    townName: "Madrid",
  },
  {id:8,
    image: "https://i.postimg.cc/MTQ9GjS8/4-Royal-Palace-1.jpg",
    townName: "Madrid",
  },
 
];

export const citiesOfTurkeyData = [
    {id:1,
      image: "https://i.postimg.cc/DZLrhXt4/Temple-Of-Augustus-Ankara.jpg",
      townName: "Ankara",
    },
    {id:2,
      image: "https://i.postimg.cc/P5C8hDDf/taksim-square.jpg",
      townName: "Istanbul",
    },
    {id:3,
      image: "https://i.postimg.cc/fbJLYQCw/hamamono-ankara.jpg",
      townName: "Ankara",
    },
    {id:4,
      image: "https://i.postimg.cc/pV7mCT7g/pexels-beyza-erdem-7596433.jpg",
      townName: "Buyukada",
    },
    {id:5,
      image: "https://i.postimg.cc/tTp3XTyr/pexels-konevi-2159549.jpg",
      townName: "Istanbul",
    },
    {id:6,
      image: "https://i.postimg.cc/DZLrhXt4/Temple-Of-Augustus-Ankara.jpg",
      townName: "Ankara",
    },
    {id:7,
      image: "https://i.postimg.cc/P5C8hDDf/taksim-square.jpg",
      townName: "Istanbul",
    },
    {id:8,
      image: "https://i.postimg.cc/fbJLYQCw/hamamono-ankara.jpg",
      townName: "Ankara",
    },
    
  ];
  
